OnlineShopApp/Models/ProductCategory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategory()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int ProductCategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}

OnlineShopApp/Models/ProductCategoryViewModel.cs
using OnlineShopApp.Validators;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace OnlineShopApp.Models
{
    public partial class ProductCategoryViewModel
    {
        public int ProductCategoryId { get; set; }

        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Display(Name = "Image")]
        [ValidationFile]
        public HttpPostedFileBase ImagePath { get; set; }

        public string ImageName { get; set; }

        public bool IsChangeImage { get; set; }
    }
}

OnlineShopApp/Areas/HelpPage/Controllers/ProductCategoriesController.cs
using OnlineShopApp.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace OnlineShopApp.Areas.HelpPage.Controllers
{
    /// <summary>
    /// API to get all information regarding product categories
    /// </summary>
    public class ProductCategoriesController : ApiController
    {
        private OnlineShopEntities db = new OnlineShopEntities();

        /// <summary>
        /// Get all the product categories
        /// </summary>
        // GET api/productcategories
        public IEnumerable<ProductCategoryViewModel> Get()
        {
            List<ProductCategoryViewModel> productCategoriesViewModel = new List<ProductCategoryViewModel>();
            foreach (var productCategory in db.ProductCategory)
            {
                productCategoriesViewModel.Add(GetProductCategoryViewModel(productCategory));
            }
            return productCategoriesViewModel;
        }

        /// <summary>
        /// Get a product category by id
        /// </summary>
        // GET api/productcategories/5
        public IHttpActionResult Get(int id)
        {
            ProductCategory productCategory = db.ProductCategory.Find(id);
            if (productCategory == null) return NotFound();
            return Ok(GetProductCategoryViewModel(productCategory));
        }

        /// <summary>
        /// Create a new product category
        /// </summary>
        // POST api/productcategories
        public HttpResponseMessage Post([FromBody] ProductCategoryViewModel productCategoryViewModel)
        {
            if (ModelState.IsValid)
            {
                ProductCategory productCategory = new ProductCategory
                {
                    Name = productCategoryViewModel.Name,
                    Description = productCategoryViewModel.Description,
                    ProductCategoryId = productCategoryViewModel.ProductCategoryId,
                    ImagePath = productCategoryViewModel.ImageName
                };
                db.ProductCategory.Add(productCategory);
                db.SaveChanges();
                return new HttpResponseMessage(HttpStatusCode.OK);
            }

            return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
        }

        /// <summary>
        /// Update a given product category
        /// </summary>
        // PUT api/productcategories/5
        public HttpResponseMessage Put(int id, [FromBody] ProductCategoryViewModel productCategoryViewModel)
        {
            if (ModelState.IsValid)
            {
                ProductCategory productCategory = db.ProductCategory.Find(id);
                if (productCategory == null)
                {
                    ModelState.AddModelError("ProductCategoryId", "Not found key");
                    return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
                }
                productCategory.Name = productCategoryViewModel.Name;
                productCategory.Description = productCategoryViewModel.Description;
                productCategory.ProductCategoryId = productCategoryViewModel.ProductCategoryId;
                productCategory.ImagePath = productCategoryViewModel.ImageName;
                db.Entry(productCategory).State = EntityState.Modified;
                db.SaveChanges();
                return new HttpResponseMessage(HttpStatusCode.OK);
            }

            return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
        }

        /// <summary>
        /// Delete a given product category
        /// </summary>
        // DELETE api/productcategories/5
        public HttpResponseMessage Delete(int id)
        {
            ProductCategory productCategory = db.ProductCategory.Find(id);
            if (productCategory == null)
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
            }
            db.ProductCategory.Remove(productCategory);
            db.SaveChanges();
            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        private ProductCategoryViewModel GetProductCategoryViewModel(ProductCategory productCategory)
        {
            return new ProductCategoryViewModel
            {
                ProductCategoryId = productCategory.ProductCategoryId,
                Name = productCategory.Name,
                Description = productCategory.Description,
                ImagePath = null,
                ImageName = productCategory.ImagePath,
                IsChangeImage = false
            };
        }
    }
}

OnlineShopApp/Controllers/ProductsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using OnlineShopApp.Models;
using OnlineShopApp.Helpers;
using System.Collections.Generic;
using System;

namespace OnlineShopApp.Controllers
{
    public class ProductsController : Controller
    {
        private OnlineShopEntities db = new OnlineShopEntities();

        // GET: Products
        public ActionResult Index()
        {
            var product = db.Product.Include(p => p.ProductCategory);
            return View(product.ToList());
        }

        // GET: Products/List
        public ActionResult List()
        {
            return PartialView(db.Product.ToList());
        }

        // GET: Products/ListByCategoryId/5
        public ActionResult ListByCategoryId(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.CategoryName = db.ProductCategory.Find(id).Name;
            return View(db.Product.Where(p => p.ProductCategoryId == id).ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles = RoleConstants.Admin)]
        public ActionResult Create()
        {
            ViewBag.ProductCategoryId = new SelectList(db.ProductCategory, "ProductCategoryId", "Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleConstants.Admin)]
        public ActionResult Create([Bind(Include = "ProductId,Name,ProductCategoryId,Price,Quantity,Description,ImagePath")] ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                var myHelper = new ControllersHelper();
                var imagePath = myHelper.SaveFile(productViewModel.ImagePath, ModelState, Server);

                Product product = new Product
                {
                    Name = productViewModel.Name,
                    Description = productViewModel.Description,
                    Price = productViewModel.Price,
                    Quantity = productViewModel.Quantity,
                    ProductCategoryId = productViewModel.ProductCategoryId,
                    ImagePath = imagePath
                };
                db.Product.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductCategoryId = new SelectList(db.ProductCategory, "ProductCategoryId", "Name", productViewModel.ProductCategoryId);
            return View(productViewModel);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = RoleConstants.Admin)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            var productCategories = new List<SelectListItem>();
            foreach (var productCategory in db.ProductCategory)
            {
                productCategories.Add(new SelectListItem()
                {
                    Text = productCategory.Name,
                    Value = productCategory.ProductCategoryId.ToString(),
                    // Put all sorts of business logic in here
                    Selected = product.ProductCategoryId == productCategory.ProductCategoryId ? true : false
                });
            }
            ProductViewModel productViewModel = new ProductViewModel
            {
                ProductId = id.Value,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                Quantity = product.Quantity,
                ImageName = product.ImagePath,
                ProductCategories = productCategories,
                ProductCategoryId = product.ProductCategoryId
            };
            return View(productViewModel);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleConstants.Admin)]
        public ActionResult Edit([Bind(Include = "ProductId,Name,ProductCategoryId,Price,Quantity,Description,ImagePath,ImageName,IsChangeImage")] ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                var imagePath = productViewModel.ImageName;
                if (productViewModel.IsChangeImage)
                {
                    var myHelper = new ControllersHelper();
                    imagePath = myHelper.SaveFile(productViewModel.ImagePath, ModelState, Server);
                }

                Product product = new Product
                {
                    ProductId = productViewModel.ProductId,
                    Name = productViewModel.Name,
                    Description = productViewModel.Description,
                    Price = productViewModel.Price,
                    Quantity = productViewModel.Quantity,
                    ProductCategoryId = productViewModel.ProductCategoryId,
                    ImagePath = imagePath
                };
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductCategoryId = new SelectList(db.ProductCategory, "ProductCategoryId", "Name", productViewModel.ProductCategoryId);
            return View(productViewModel);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = RoleConstants.Admin)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleConstants.Admin)]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Product.Find(id);
            try
            {
                db.Product.Remove(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Error! An error has occured. May be related to a Purchase associated with this Product.");
            }
            
            return View(product);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShopApp/Views/ProductCategories/Create.cshtml
@model OnlineShopApp.Models.ProductCategoryViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Product Category - Create</h2>


@using (Html.BeginForm("Create", "ProductCategories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { cols = 35, @rows = 3, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImagePath, new { type = "file", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 clearfix">
                <input type="submit" value="Create" class="btn btn-success float-right my-button" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-success my-button" href="@Url.Action("Index", "ProductCategories")"><i class="fas fa-arrow-alt-circle-left"></i> Back to List</a>
    <div class="margin-top-10px"></div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineShopApp/Views/ProductCategories/Delete.cshtml
@model OnlineShopApp.Models.ProductCategory

@{
    ViewBag.Title = "Delete";
}

<h2>Product Category - Delete</h2>

<h3>Are you sure you want to delete this?</h3>
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Image
        </dt>

        <dd>
            @if (!string.IsNullOrWhiteSpace(Model.ImagePath))
            {
                <img src="@Url.Content("~/Content/Images/Upload/" + Model.ImagePath)" alt="computer-icon" class="image-dimens-48px" />
            }
            else
            {
                <i class="fas fa-th big-icon"></i>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <div class="clearfix">
                <input type="submit" value="Delete" class="btn btn-success my-button float-right" />
            </div>
            <a class="btn btn-success my-button" href="@Url.Action("Index", "ProductCategories")"><i class="fas fa-arrow-alt-circle-left"></i> Back to List</a>
            <div class="margin-top-10px"></div>
        </div>
    }
</div>

OnlineShopApp/Views/ProductCategories/Details.cshtml
@model OnlineShopApp.Models.ProductCategory

@{
    ViewBag.Title = "Details";
}

<h2>Product Category - Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Image
        </dt>

        <dd>
            @if (!string.IsNullOrWhiteSpace(Model.ImagePath))
            {
                <img src="@Url.Content("~/Content/Images/Upload/" + Model.ImagePath)" alt="computer-icon" class="image-dimens-48px" />
            }
            else
            {
                <i class="fas fa-th big-icon"></i>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<p>
    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        <div class="clearfix">
            <a class="btn btn-success my-button float-right" href="@Url.Action("Edit", "ProductCategories", new { id = Model.ProductCategoryId })">Edit</a>
        </div>
        <div class="margin-top-10px"></div>
    }
    <a class="btn btn-success my-button" href="@Url.Action("Index", "ProductCategories")"><i class="fas fa-arrow-alt-circle-left"></i> Back to List</a>
</p>

OnlineShopApp/Views/ProductCategories/Edit.cshtml
@model OnlineShopApp.Models.ProductCategoryViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Product Category - Edit</h2>


@using (Html.BeginForm("Edit", "ProductCategories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductCategoryId)
        @Html.HiddenFor(model => model.ImageName)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { cols = 35, @rows = 3, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="margin-top-10px"></div>
            <div class="control-label col-md-2">
                @if (!string.IsNullOrWhiteSpace(Model.ImageName))
                {
                    <img src="@Url.Content("~/Content/Images/Upload/" + Model.ImageName)" alt="computer-icon" class="image-dimens-48px" />
                }
                else
                {
                    <i class="fas fa-th big-icon"></i>
                }
            </div> 
            <div class="margin-top-10px"></div>
            <div class="control-label col-md-10">
                @Html.CheckBox("IsChangeImage", false)
                <label class="form-check-label" for="exampleCheck1">Select if you want to change the image</label>
            </div>
            <div class="col-md-10 image-edit-input">
                <div class="margin-top-10px"></div>
                @Html.TextBoxFor(model => model.ImagePath, new { type = "file", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
            
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 clearfix">
                <input type="submit" value="Save" class="btn btn-success float-right my-button" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-success my-button" href="@Url.Action("Index", "ProductCategories")"><i class="fas fa-arrow-alt-circle-left"></i> Back to List</a>
    <div class="margin-top-10px"></div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineShopApp/Views/ProductCategories/Index.cshtml
@model IEnumerable<OnlineShopApp.Models.ProductCategory>

@{
    ViewBag.Title = "Index";
}

<h2>Product Category - List</h2>

@if (Request.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <div class="clearfix">
            @Html.ActionLink("Create", "Create", "ProductCategories", null, new { @class = "btn btn-success float-right my-button" })
        </div>
        <div class="margin-top-10px"></div>
    </p>
}
<table class="table table-bordered table-hover text-center">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                Image
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th scope="col">Operations</th>
        </tr>
    </thead>

    @foreach (var item in Model) {
        <tr>
            <td>
                @if (!string.IsNullOrWhiteSpace(item.ImagePath))
                {
                    <img src="@Url.Content("~/Content/Images/Upload/" + item.ImagePath)" alt="computer-icon" class="image-dimens-48px" />
                }
                else
                {
                    <i class="fas fa-th big-icon"></i>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a href="@Url.Action("Edit", "ProductCategories", new { id = item.ProductCategoryId })"><i class="big-icon fas fa-pencil-alt"></i></a> <span>&nbsp;</span>
                }
                <a href="@Url.Action("Details", "ProductCategories", new { id=item.ProductCategoryId })"><i class="big-icon far fa-file-alt"></i></a> &nbsp;
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a href="@Url.Action("Delete", "ProductCategories", new { id = item.ProductCategoryId })" ><i class="big-icon far fa-trash-alt"></i></a>
                }
            </td>
        </tr>
    }

</table>

OnlineShopApp/Views/ProductCategories/List.cshtml
@model IEnumerable<OnlineShopApp.Models.ProductCategory>

<div class="list-group">
@foreach (var item in Model)
{
    <a href="@Url.Action("ListByCategoryId", "Products", new { @id = item.ProductCategoryId })" class="list-group-item">
        @if (!string.IsNullOrWhiteSpace(item.ImagePath))
        {
            <img class="image-dimens-48px" src="@Url.Content("~/Content/Images/Upload/" + item.ImagePath)" alt="product-category" />
        }
        else
        {
            <i class="fas fa-th big-icon"></i>
        }
        @item.Name
    </a>
}
</div>