OnlineShopApp/Controllers/CheckoutController.cs
using Microsoft.AspNet.Identity;
using OnlineShopApp.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace OnlineShopApp.Controllers
{
    [Authorize(Roles = RoleConstants.Client)]
    public class CheckoutController : Controller
    {
        private OnlineShopEntities db = new OnlineShopEntities();

        // GET: Checkout
        public ActionResult Index(CheckoutPurchase checkoutPurchase)
        {
            ViewBag.TotalPrice = checkoutPurchase.Sum(cp => cp.ProductPrice * cp.Quantity);
            return View(checkoutPurchase);
        }

        public ActionResult AddProduct(CheckoutPurchase checkoutPurchase, int productId, string clientName, int quantity = 0)
        {
            Product product = db.Product.Find(productId);
            CheckoutProduct myCheckoutPurchase = new CheckoutProduct
            {
                Index = checkoutPurchase.Count,
                ProductId = product.ProductId,
                ProductName = product.Name,
                ProductImage = product.ImagePath,
                ClientName = clientName,
                ProductPrice = product.Price,
                Quantity = quantity
            };
            checkoutPurchase.Add(myCheckoutPurchase);

            return RedirectToAction("Index", "Products");
        }

        public ActionResult QuantityProducts(CheckoutPurchase checkoutPurchase)
        {
            return PartialView(checkoutPurchase);
        }

        public ActionResult Buy(CheckoutPurchase checkoutPurchase)
        {
            Product product;
            foreach(var item in checkoutPurchase)
            {
                product = db.Product.Find(item.ProductId);
                if (product != null)
                {
                    // update quantities products
                    product.Quantity -= item.Quantity;
                    db.Product.Attach(product);
                    db.Entry(product).Property(p => p.Quantity).IsModified = true;

                    // add new purchase
                    Purchase purchase = new Purchase
                    {
                        ClientId = User.Identity.GetUserId(),
                        ProductId = item.ProductId,
                        StorageDate = DateTime.Now
                    };
                    db.Purchase.Add(purchase);
                    db.SaveChanges();   
                }
                else
                {
                    return View(checkoutPurchase);
                }
            }
            checkoutPurchase.Clear();
            return RedirectToAction("Index", "Products");
        }

        // GET: Checkout/Edit/5
        public ActionResult Edit(CheckoutPurchase checkoutPurchase, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            checkoutPurchase[id.Value].Index = id.Value;
            return View(checkoutPurchase[id.Value] as CheckoutProduct);
        }

        // POST: Checkout/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Index,ProductId,ProductName,ProductImage,ClientName,ProductPrice,Quantity")] CheckoutProduct checkoutProductViewModel,
            CheckoutPurchase checkoutPurchase)
        {
            if (ModelState.IsValid)
            {
                Product product = db.Product.Find(checkoutProductViewModel.ProductId);
                if (product.Quantity >= checkoutProductViewModel.Quantity)
                {
                    checkoutPurchase[checkoutProductViewModel.Index].Quantity = checkoutProductViewModel.Quantity;
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("Quantity", "Error! Quantity cannot be higher than stock available");
                }
            }
            return View(checkoutProductViewModel);
        }

        // GET: Checkout/Delete/5
        public ActionResult Delete(CheckoutPurchase checkoutPurchase, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(checkoutPurchase[id.Value] as CheckoutProduct);
        }

        // POST: Checkout/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(CheckoutPurchase checkoutPurchase, int id)
        {
            checkoutPurchase.RemoveAt(id);
            return RedirectToAction("Index");
        }
    }
}

OnlineShopApp/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShopApp.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using static OnlineShopApp.Controllers.ManageController;
using OnlineShopApp.Helpers;
using System.Threading.Tasks;

namespace OnlineShopApp.Controllers
{
    public class UsersController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        private ApplicationDbContext db;
        private OnlineShopEntities onlineShopDB;

        public UsersController()
        {
            db = new ApplicationDbContext();
            onlineShopDB = new OnlineShopEntities();
        }

        public UsersController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Users
        public ActionResult Index()
        {
            List<ApplicationUser> appUsers = db.Users.ToList();
            List<UserViewModel> model = new List<UserViewModel>();
        
            foreach (ApplicationUser appUser in appUsers)
            {
                var myHelper = new ControllersHelper();
                model.Add(myHelper.GetUserViewModel(appUser, db, UserManager));
            }
            return View(model);
        }

        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser appUser = db.Users.Where(u => u.Id == id).FirstOrDefault();
            if (appUser == null)
            {
                return HttpNotFound();
            }
            var myHelper = new ControllersHelper();
            return View(myHelper.GetUserViewModel(appUser, db, UserManager));
        }

        // GET: Users/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Email,UserName,SelectedRoleName,Password")] UserViewModel userViewModel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.UserViewModels.Add(userViewModel);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(userViewModel);
        //}

        // GET: Users/Edit/5
        [Authorize(Roles = RoleConstants.Admin)]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser appUser = db.Users.Where(u => u.Id == id).FirstOrDefault();
            if (appUser == null)
            {
                return HttpNotFound();
            }
            var myHelper = new ControllersHelper();
            return View(myHelper.GetUserViewModel(appUser, db, UserManager));
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleConstants.Admin)]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Email,UserName,SelectedRoleName,NewPassword,OldPassword,ConfirmPassword")]
            UserViewModel model)
        {
            var myHelper = new ControllersHelper();
            if (!ModelState.IsValid)
            {
                model.RoleChoices = db.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
                model.SelectedRoleName = UserManager.GetRoles(model.Id).FirstOrDefault();
                return View(model);
            }
            var result = await UserManager.ChangePasswordAsync(model.Id, model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                
                var roles = await UserManager.GetRolesAsync(model.Id);
                IdentityResult resultRole = await UserManager.RemoveFromRolesAsync(model.Id, roles.ToArray());
                if (resultRole.Succeeded)
                {
                    // add role
                    await this.UserManager.AddToRoleAsync(user.Id, model.SelectedRoleName);

                    user.UserName = model.UserName;
                    user.Email = model.Email;
                    IdentityResult resultUser = UserManager.Update(user);
                    if (resultUser.Succeeded)
                    {
                        return RedirectToAction("Index", new { Message = ManageMessageId.ChangePasswordSuccess });
                    }
                }
            }
            model.RoleChoices = db.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            model.SelectedRoleName = UserManager.GetRoles(model.Id).FirstOrDefault();
            AddErrors(result);
            return View(model);
        }

        // GET: Users/Delete/5
        [Authorize(Roles = RoleConstants.Admin)]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser appUser = db.Users.Where(u => u.Id == id).FirstOrDefault();
            if (appUser == null)
            {
                return HttpNotFound();
            }
            var myHelper = new ControllersHelper();
            return View(myHelper.GetUserViewModel(appUser, db, UserManager));
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleConstants.Admin)]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser appUser = db.Users.Where(u => u.Id == id).FirstOrDefault();
            var isPurchaseForClientExists = onlineShopDB.Purchase.Any(p => p.ClientId == appUser.Id);
            if (isPurchaseForClientExists)
            {
                ModelState.AddModelError("", "Error! An error has occured. May be related to a Purchase associated with this Client.");
                var myHelper = new ControllersHelper();
                return View(myHelper.GetUserViewModel(appUser, db, UserManager));
            }
            db.Users.Remove(appUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Helpers
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
        #endregion
    }
}

OnlineShopApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Online Shop - GM</title>

    <!-- Favicon image -->
    <link rel="icon" href="@Url.Content("~/Content/Images/favicon.png")">
    <!-- Bootstrap, Fontawesome, Custom styles load -->
    @Styles.Render("~/Content/css")
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <img src="@Url.Content("~/Content/Images/cart-icon.png")" alt="cart icon" class="logo-main" />
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Online Shop
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <span>- Admin <i class="fas fa-user"></i></span>
                }
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    @if (Request.IsAuthenticated && User.IsInRole("Client"))
                    {
                        <li class="nav-item">
                            @{ 
                                int quantityCheckout = 0;
                                Int32.TryParse(@Html.Action("QuantityProducts", "Checkout").ToString(), out quantityCheckout);
                            }
                            @if (quantityCheckout == 0)
                            {
                                <a class="nav-link" href="@Url.Action("Index", "Checkout")"><i class="fas fa-shopping-cart"></i> (@quantityCheckout)</a>
                            }
                            else
                            {
                                <a class="nav-link" href="@Url.Action("Index", "Checkout")"><i class="fas fa-cart-plus"></i> (@quantityCheckout)</a>
                            }
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Users")"><i class="fas fa-users"></i> Clients</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Products")"><i class="fas fa-desktop"></i> Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "ProductCategories")"><i class="fas fa-th"></i> Product Catgs</a>
                    </li>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Help")"><i class="fas fa-rocket"></i> API</a>
                        </li>
                    }
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <a href="@Url.Action("Index", "Home")" alt="index">
                    <img src="@Url.Content("~/Content/Images/shopping-basket-icon.jpg")" alt="shopping-basket" class="logo-basket" />
                </a>
                <div class="margin-top-10px"></div>
                @Html.Action("List", "ProductCategories")
            </div>

            <div class="col-lg-9">

                <div class="margin-top-50px"></div>
                @RenderBody()
            </div>
            <!-- /.col-lg-9 -->

        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Author: Gabriel Muñumel - Online Shop ☺</p>
        </div>
        <!-- /.container -->
    </footer>
    <!-- Bootstrap, Jquery core JavaScript -->
    @Scripts.Render("~/Scripts/js")
    @RenderSection("scripts", required: false)
</body>
</html>